name: Test01
version: 1.14-SNAPSHOT
api-version: 1.19
main: harry1725.com.test01.test
author: Derman_e
description: Derman_e 수제 공부용 플러그인.

commands:
  hehe:
    description: 플러그인 메인 커맨드입니다.

  test:
    description: 콘솔용 플러그인 커맨드입니다.